### ISSUE TITLE
AttributeError: 'CodeReader' object has no attribute 'set_pos'

### ISSUE THREAD

**Issue by naro** [MightyPork/sdscp#1]
Code test.c (the code is wrong, semicolon is missing after sys[196] = 2). I do expect some Syntax error from sdscp.

```
init() {
    sys[196] = 2
}

main() {}
```

Command:
```sdscp test.c -d```

Output:
```
# sdscp test.c -d

:::::::::::::::::::::::::::::: SDS-C Preprocessor ::::::::::::::::::::::::::::::

Reading file: test.c
Resolving directives...
Applying macros...
Tokenizing code...
Traceback (most recent call last):
  File "/Users/naro/work/SDS/sdscp/sdscp", line 218, in <module>
    tokens = tk.tokenize()
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 967, in tokenize
    t.tokenize()
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 51, in tokenize
    self._tokenize()
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 876, in _tokenize
    self.tokens = rd.tokenize()
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 948, in tokenize
    self._tokenize_identifier(rd)
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 1296, in _tokenize_identifier
    self._collect_assign_stmt(rd)
  File "/Users/naro/work/SDS/sdscp_1-3-3/tokens.py", line 1005, in _collect_assign_stmt
    T_Rvalue(rd.consume_rvalue())
  File "/Users/naro/work/SDS/sdscp_1-3-3/readers.py", line 852, in consume_rvalue
    buffer += self.consume_code(end=[';', ','], consume_end=False)
  File "/Users/naro/work/SDS/sdscp_1-3-3/readers.py", line 639, in consume_code
    self.set_pos(pos_begin)
AttributeError: 'CodeReader' object has no attribute 'set_pos'
```

The method 'set_pos' is not defined anywhere but called on few places in the code.

Thank you for sdscp. It makes SDS programming much more readable and fun :)

**Comment by MightyPork** [comment]
Should be fixed now.

**Comment by naro** [comment]
Thanks, works like a charm. I can make much more errors now!
